name: CI

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version}}

    - name: packages installation
      run: |
        npm install
    - name: npm test
      run: |
        npm test
    - id: commit
      uses: pr-mpt/actions-commit-hash@v1
    - name: commit id
      env:
        COMMIT_ID: ${{ steps.commit.outputs.short }}
      run: |
        echo $COMMIT_ID
