name: CI

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version}}
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1.6.1
    #   with:
    #     aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
    #     # role-to-assume: ${{ secrets.DEV_AWS_ROLE_TO_ASSUME }}
    #     aws-region: ap-south-1
    - name: packages installation
      run: |
        npm install
    - name: npm test
      run: |
        npm test
    # - id: commit
    #   uses: pr-mpt/actions-commit-hash@v1
    - name: commit id
      env:
        COMMIT_ID: ${{ github.commit_sha }}
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        echo $COMMIT_ID
        echo $USER_NAME
